// Copies the compiled contract ABI from Foundry's output into the web app and oracle bot.
// Run `forge build` in contracts/ first.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = resolve(root, "contracts/out/FlightDelayInsurance.sol/FlightDelayInsurance.json");
const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
const source = `// Generated by scripts/export-abi.mjs from contracts/out. Do not edit.\nexport const fdiAbi = ${JSON.stringify(abi, null, 2)} as const;\n`;

for (const target of ["web/src/lib/abi.ts", "oracle-bot/src/abi.ts"]) {
  writeFileSync(resolve(root, target), source);
  console.log(`Wrote ${abi.length} ABI entries to ${target}`);
}
